#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

p_d_s () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    p_d_s "$2.$1" "$2"
else
    p_d_s "www.$1" "www"
    p_d_s "lb-01.$1" "lb-01"
    p_d_s "web-01.$1" "web-01"
    p_d_s "web-02.$1" "web-02"
fi
