#!/bin/bash
# shellcheck disable=SC2009

# Display lines containing the word 'bash' to find the PID of the Bash process

# Use ps command to list processes and grep for lines containing 'bash'
ps aux | grep bash
