#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.

# Use the 'ip' command to show all active interfaces and their IPs
ip -4 addr show | awk '/inet / {print $2}' | cut -d'/' -f1

